version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/testcode

permissions:
  - object: /home/ubuntu/testcode
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: ubuntu
